source 'http://rubygems.org/'

gem 'page-object'
gem 'activesupport'
gem 'rake'
gem 'rspec'
gem 'foo'
gem 'rubocop'
gem 'watir'
gem 'bridge'
gem 'ffi'
gem 'roo'
gem 'roo-xls'
gem 'require_all'
gem 'selenium-webdriver', '4.1.0'
gem 'jruby-win32ole'
gem 'cucumber', '3.1.2'
gem 'nokogiri'
gem 'time'
gem 'fileutils'
gem 'write_xlsx'
gem 'rubyXL'
gem 'spreadsheet'
gem 'json'